baseURL = "https://qkzk.xyz/"
languageCode = "en-us"
title = "qkzk"
theme = "book"
BookDateFormat = '2-1-2006'


# pygmentsstyle = "b2"
pygmentsstyle = "manni"
# pygmentsstyle = "murphy"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
author = "qkzk"
description = "Informatique et mathématiques"
minify = "true"
BookTheme = 'light'


[menu]

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
[privacy.instagram]
disable = true
[privacy.twitter]
disable = true
[privacy.vimeo]
disable = true
[privacy.youtube]
disable = true

[permalinks]
docs = "/"

[markup.goldmark.renderer]
unsafe = true
