baseURL = "http://qkzk.github.io/"
languageCode = "en-us"
title = "qkzk"
theme = "book"
BookDateFormat = '2-1-2006'


# pygmentsstyle = "b2"
pygmentsstyle = "manni"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "qkzk"
  description = "Informatique au Lycée des Flandres"
  minify = "true"


[menu]
  [[menu.banner]]
    identifier = "isn"
    name = "isn"
    url = "/docs/isn"
    weight = 2

  [[menu.banner]]
    identifier = "nsi"
    name = "nsi"
    url = "/docs/nsi"
    weight = 1

  [[menu.banner]]
    identifier = "collegues"
    name = "collegues"
    url = "/docs/collegues"
    weight = 3

  [[menu.banner]]
    identifier = "ressources"
    name = "ressources"
    url = "/docs/ressources"
    weight = 4

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[permalinks]
  docs = "/"
