baseURL = "https://qkzk.xyz/"
languageCode = "en-us"
title = "qkzk"
theme = "book"
BookDateFormat = '2-1-2006'


pygmentsstyle = "manni"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
description = "Informatique et mathématiques"
minify = "true"
BookTheme = 'light'
[security]
allowContent = ['text/html$', 'text/markdown$']
enableInlineShortcodes = false
[security.exec]
allow = [
  '^(dart-)?sass(-embedded)?$',
  '^go$',
  '^git$',
  '^node$',
  '^postcss$',
  '^tailwindcss$',
]
osEnv = [
  '(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$',
]
[security.funcs]
getenv = ['^HUGO_', '^CI$']
[security.http]
methods = ['(?i)GET|POST']
urls = [
  '(?i)^https?://[a-z0-9]',
  '! ^https?://\d+\.',
  '! (?i)localhost',
  '! (?i)^https?://[^/?#]*@',
]
[security.node]
[security.node.permissions]
allowAddons = ['tailwindcss']
allowChildProcess = ['tailwindcss']
allowRead = ['.']
allowWorker = ['tailwindcss']
allowWrite = []
disable = false

[menu]

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
[privacy.instagram]
disable = true
[privacy.x]
disable = true
[privacy.vimeo]
disable = true
[privacy.youtube]
disable = true

[permalinks]

[markup.goldmark.renderer]
unsafe = true
